[.NET MAUI Beautiful UI Challenge] HeartsCounter App
jsuarezruiz/net-maui-goodlooking-UI pull request #32
Opened 2022-09-07 22:51 UTC by flipper09112

### .NET MAUI Beautiful UI Challenge (August 2022)

If you're submitting this during August 2022, you can enter in the [.NET MAUI Beautiful UI Challenge](https://aka.ms/maui/uichallenge)! After submitting your pull request, grab the URL and fill out the quick form at https://www.surveymonkey.com/r/maui-ui-challenge to let us know where to send your stickers!

2022-09-08 14:02 UTC, jsuarezruiz requested changes

2022-09-08 14:02 UTC, jsuarezruiz commented
![image](https://user-images.githubusercontent.com/6755973/189142429-3d423c83-539b-4945-b8b7-1886bf6c8b22.png)

2022-09-08 17:21 UTC, flipper09112 commented on README.md
> +![HeartsCounter](https://user-images.githubusercontent.com/103980/187330554-af91ea49-fd0f-423b-a283-ef5f4ba16e0a.png)
i forgot remove this. Its resolved 👍

2022-10-16 17:10 UTC, jsuarezruiz requested changes
Could you review the conflicts? Thanks.

2024-02-08 18:14 UTC, closed without merging